### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by theskyfloor** [fromtheoutfit/navee#3]
Ability to access entries to edit (both through a link and the pop-over modal) and see their URL's from the node structure page.

**Comment by theskyfloor** [comment]
And actually it would be really really helpful to set a destination in the control panel for a node so that when you click on the edit button it could direct you somewhere like the index for a blog channel, etc.

**Comment by michaelfromtheoutfit** [comment]
Yeah - I played around with having the URLs visible from the node structure page. Unfortunately when either the navigation got past a few levels (or if the url was pretty long - say for an asset hosted on s3) the interface became super cluttered.

I definitely think having a link somewhere to quickly jump to the entry to edit would be a great addition though.

**Comment by michaelfromtheoutfit** [comment]
Ok, so there are now links to the element edit page in the CP for any entries/categories/assets type nodes. 

This is completed in [v1.0.3](https://github.com/fromtheoutfit/navee/releases/tag/v1.0.3)

For now, we aren't going to put the full url in the node structure page, because it severely limits spacing.
