### ISSUE TITLE
Is customization of 'children' possible?

### ISSUE THREAD

**Issue by simplethemes** [fromtheoutfit/navee#5]
First off, thank you for releasing this plugin to the public. Your work is truly appreciated!

I noticed that navee basically uses the [{% nav %}](https://craftcms.com/docs/templating/nav) tag within a custom structure. This may be more of a CMS/Twig question, but I was wondering, would it possible to add a custom Twig extension to bypass the `{% children %}` tag?

My client has what I guess you'd call a "mega menu" wherein the submenus are split into columns and I'd really like to go a little deeper into the template layer with various wrappers for columns and other logic.

This was a missing feature in the EE version, but perhaps these resources will help now that we have better access to things?

**Comment by michaelfromtheoutfit** [comment]
Hey @simplethemes!

I'm off on a few days vacation until after Memorial Day (returning Tuesday). I'd love to chat more about what the best method to get this working for you would be. I'll hit you up as soon as I am back.

MW

**Comment by jausura** [comment]
Hey @simplethemes, 

This is something other folks have brought up in the past, so we took a little time to document the solution. Here's a tutorial style blog post: https://fromtheoutfit.com/updates/custom-fields-and-navee-for-craft.

The trick is to add custom fields to your navigation and use them as hooks to designate sections of your nav tree as buckets for markup wrappers instead of ancestors in the nav. Give it a read and let me know if that works for your menu.

**Comment by simplethemes** [comment]
My apologies for just now getting around to saying thank you for the detailed tutorial. I really appreciate your work!
